# Generated by Django 4.1.3 on 2023-01-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=50)),
                ('volumen', models.IntegerField()),
                ('cosecha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=50)),
                ('volumen', models.IntegerField()),
                ('cosecha', models.CharField(max_length=50)),
            ],
        ),
    ]
